project:
  type: website
  output-dir: docs

website:
  title: "Refugees in Kenya"
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Home
      - analysis.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



