/* This SPSS program was automatically generated by Stat/Transfer ver.17.0.1718.0616 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\wer.dat" ENCODING="CP1252" / LRECL=272 .

DATA LIST FILE=DATA/
   hhid 1-9                 hhmemid 10-11            strata_sampled 12     
   strata_actual 13         groups_location_status 14   groups_status 15      
   weight_wer 16-32         c1_age1a 33-34           c1_statusa1 35        
   c1_attendedschool 36     c1_educlevelcat 37    
   c1_neverattendsch_schoolcost 38   c1_neverattendsch_lacktoilet 39
   c1_neverattendsch_lackteachers 40   c1_neverattendsch_illness 41
   c1_neverattendsch_disability 42   c1_neverattendsch_famillness 43
   c1_neverattendsch_famdisability 44   c1_neverattendsch_nointerest 45
   c1_neverattendsch_parents 46   c1_neverattendsch_hadtowork 47
   c1_neverattendsch_toofar 48   c1_neverattendsch_sanitary 49
   c1_neverattendsch_conflicts 50   c1_neverattendsch_insecurity 51
   c1_neverattendsch_safety 52   c1_neverattendsch_marriage 53
   c1_neverattendsch_teachers 54   c1_neverattendsch_pregnancy 55
   c1_neverattendsch_notadmit 56   c1_neverattendsch_pressure 57
   c1_neverattendsch_orphaned 58   c1_neverattendsch_identificat 59
   c1_neverattendsch_declined 60   c1_neverattendsch_dk 61
   c2_countrylivedin 62     c2_bornraisedke 63    
   c2_differentcountrylivedin 64   c2_countryresidedin 65
   c2_countryresidedin_other 66-77 (A)   c2_whenlivein_startyear 78-81
   c2_whenlivein_endyear 82-85   c2_isitorigincountry 86
   c2_origincountry 87      c2_raisedin 88           c2_whereraised 89     
   c2_arrivedcurrresidence 90-93   c2_maritalstatus 94   
   c2_marriageplace 95      c2_marriageyr 96-97      c2_mainoccupation 98-100
   c2_mainoccupationcountry 101   c2_mainoccupationorigin 102-104
   c2_pastyearlivingstatus 105   c2_child_biological 106
   c2_child_nonbiological 107   c2_child_notlivewithme 108
   c2_child_no 109          c2_child_declined 110    c2_child_dk 111       
   c2_receivepayment 112    c2_wifeabuse_none 113    c2_wifeabuse_goesout 114
   c2_wifeabuse_neglects 115   c2_wifeabuse_argues 116   c2_wifeabuse_sex 117  
   c2_wifeabuse_food 118    c2_wifeabuse_declined 119   c2_wifeabuse_dk 120   
   c2_marriageage 121       c2_womanmarriageagelstresided 122
   c2_womanmarriageagecountorig 123   c2_readnewsoften 124  
   c2_readnewspaperfreqsltreside 125   c2_readnewspapercountorigin 126
   c2_listenradiofreq 127   c2_listenradiolstresided 128
   c2_listenradiocountorigin 129   c2_internetaccessfreq 130
   c2_internetaccesslstresided 131   c2_internetaccesscountorigin 132
   c2_watchtvfreq 133       c2_watchtvfreqlastresided 134
   c2_watchtvcountryoforigin 135   c2_fpmethod_femalesterile 136
   c2_fpmethod_malesterile 137   c2_fpmethod_iud 138   
   c2_fpmethod_injectable 139   c2_fpmethod_implants 140
   c2_fpmethod_pill 141     c2_fpmethod_malecondom 142
   c2_fpmethod_femalecondom 143   c2_fpmethod_lam 144   
   c2_fpmethod_rhythm 145   c2_fpmethod_withdrawal 146
   c2_fpmethod_econtraception 147   c2_heardofmethods 148 
   c2_fcircumcisionacceptlstreside 149   c2_fcircumcisionacceptorigin 150
   c2_fcircumcisionacceptcomunity 151   c2_fcircumcisioncontinuity 152
   c2_fpsourcelstfewmnth_radio 153   c2_fpsourcelstfewmnth_tv 154
   c2_fpsourcelstfewmnth_news 155   c2_fpsourcelstfewmnth_social 156
   c2_fpsourcelstfewmnth_internet 157   c2_fpsourcelstfewmnth_none 158
   c2_fpsourcelstfewmnth_declined 159   c2_fpsourcelstfewmnth_dk 160
   c2_fpsourcelst12mnth_pforums 161   c2_fpsourcelst12mnth_posters 162
   c2_fpsourcelst12mnth_hworker 163   c2_fpsourcelst12mnth_social 164
   c2_fpsourcelst12mnth_email 165   c2_fpsourcelst12mnth_political 166
   c2_fpsourcelst12mnth_none 167   c2_fpsourcelst12mnth_declined 168
   c2_fpsourcelst12mnth_dk 169   c2_canacquirecondoms 170
   c2_acquirecondomslstreside 171   c2_acquirecondomcountorigin 172
   c2_everheardaids 173     c2_heardaidsfrom 174     c2_reducegetgaids_none 175
   c2_reducegetgaids_sexpartner 176   c2_reducegetgaids_condom 177
   c2_reducegetgaids_nosex 178   c2_reducegetgaids_decline 179
   c2_reducegetgaids_dk 180   c2_scenariogetaids_none 181
   c2_scenariogetaids_sexpartner 182   c2_scenariogetaids_condom 183
   c2_scenariogetaids_nosex 184   c2_scenariogetaids_decline 185
   c2_scenariogetaids_dk 186   c2_healthypersonhaveaids 187
   c2_mombabyaidstrans_none 188   c2_mombabyaidstrans_preg 189
   c2_mombabyaidstrans_delivery 190   c2_mombabyaidstrans_breast 191
   c2_mombabyaidstrans_declined 192   c2_mombabyaidstrans_dk 193
   c2_partnerearningsdecision 194   c2_partnerearncountorigin 195
   c2_partnerearnlstresided 196   c2_yourearningsdecision 197
   c2_yourearningscountorigin 198   c2_yourearningslstresided 199
   c2_seekpermonwrk_no 200   c2_seekpermonwrk_partner 201
   c2_seekpermonwrk_father 202   c2_seekpermonwrk_mother 203
   c2_seekpermonwrk_brother 204   c2_seekpermonwrk_sister 205
   c2_seekpermonwrk_uncle 206   c2_seekpermonwrk_aunt 207
   c2_seekpermonwrk_son 208   c2_seekpermonwrk_daughter 209
   c2_seekpermonwrk_fatherinlaw 210   c2_seekpermonwrk_motherinlaw 211
   c2_seekpermonwrk_sombodyelse 212   c2_seekpermonwrk_decline 213
   c2_seekpermonwrk_dk 214   c2_seekpermlstresided_no 215
   c2_seekpermlstresided_partner 216   c2_seekpermlstresided_father 217
   c2_seekpermlstresided_mother 218   c2_seekpermlstresided_brother 219
   c2_seekpermlstresided_sister 220   c2_seekpermlstresided_uncle 221
   c2_seekpermlstresided_aunt 222   c2_seekpermlstresided_son 223
   c2_seekpermlstresided_daughter 224   c2_seekpermlstresided_fatherinla 225
   c2_seekpermlstresided_motherinla 226   c2_seekpermlstresided_somebodyel 227
   c2_seekpermlstresided_decline 228   c2_seekpermlstresided_dk 229
   c2_seekpermorigin_no 230   c2_seekpermorigin_partner 231
   c2_seekpermorigin_father 232   c2_seekpermorigin_mother 233
   c2_seekpermorigin_brother 234   c2_seekpermorigin_sister 235
   c2_seekpermorigin_uncle 236   c2_seekpermorigin_aunt 237
   c2_seekpermorigin_son 238   c2_seekpermorigin_daughter 239
   c2_seekpermorigin_fatherinlaw 240   c2_seekpermorigin_motherinlaw 241
   c2_seekpermorigin_somebodyelse 242   c2_seekpermorigin_decline 243
   c2_seekpermorigin_dk 244   c2_healthcaredecision 245
   c2_healthcaredecisionresid 246   c2_healthcaredecisioncountorigin 247
   c2_hhpurchasesdecision 248   c2_hhpurchasesdecisionresided 249
   c2_hhpurchasesdecisionorigin 250   c2_familyvisitsmakesdecision 251-252
   c2_famvisitdecisionlstreside 253-254   c2_famvisitdecisionorigin 255-256
   c2_notosexualintercourse 257   c2_condomusage 258    
   c3_languageused_kiswahili 259   c3_languageused_turkana 260
   c3_languageused_somali 261   c3_languageused_arabic 262
   c3_languageused_english 263   c3_languageused_jubaarabic 264
   c3_languageused_other 265   c3_speech_kiswahili 266   c3_speech_turkana 267 
   c3_speech_somali 268     c3_speech_arabic 269     c3_speech_english 270 
   c3_speech_jubaarabic 271   c3_speech_other 272 . 


FORMATS
  weight_wer (F18.15) / .

VARIABLE LABELS
   hhid '1. Unique Household Identifier'
   hhmemid 'Household Member Identifier within Household'
   strata_sampled 'Stratum based on where the household lives'
   strata_actual 'Stratum based on the where the household lives'
   groups_location_status 'Grouping based on urban/camp and refugee/host'
   groups_status 'Grouping based on urban/camp'
   weight_wer 'Sampling weight for the women empowerment respondent (WER)'
   c1_age1a 'Age of Respondent'
   c1_statusa1 'Refugee status of Respondent - Refugee or Host'
   c1_attendedschool '42. Have you ever attended school?'
   c1_educlevelcat '43. Highest level of education (category)'
   c1_neverattendsch_schoolcost '44. Reason: School cost'
   c1_neverattendsch_lacktoilet '44. Reason: Lack of toilet facility'
   c1_neverattendsch_lackteachers '44. Reason: Insufficient teachers/classrooms'
   c1_neverattendsch_illness '44. Reason: Own Illness'
   c1_neverattendsch_disability '44. Reason: Own disability'
   c1_neverattendsch_famillness '44. Reason: Family Illness'
   c1_neverattendsch_famdisability '44. Reason: Family member(s) with disability'
   c1_neverattendsch_nointerest '44. Reason: Not interested'
   c1_neverattendsch_parents '44. Reason: Parents did not let me'
   c1_neverattendsch_hadtowork '44. Reason: Had to work at home or elsewhere'
   c1_neverattendsch_toofar '44. Reason: School too far from home'
   c1_neverattendsch_sanitary    '44. Reason: Lack of sanitary towels and menstrual hygiene facilit' +
   'ies'
   c1_neverattendsch_conflicts '44. Reason: School conflicts with beliefs'
   c1_neverattendsch_insecurity '44. Reason: Insecurity and displacement'
   c1_neverattendsch_safety '44. Reason: School is not safe'
   c1_neverattendsch_marriage '44. Reason: Marriage'
   c1_neverattendsch_teachers '44. Reason: No female/male teachers'
   c1_neverattendsch_pregnancy '44. Reason: Pregnancy'
   c1_neverattendsch_notadmit '44. Reason: School did not admit me'
   c1_neverattendsch_pressure '44. Reason: Social or religious pressure'
   c1_neverattendsch_orphaned '44. Reason: Orphaned'
   c1_neverattendsch_identificat '44. Reason:  Lack of identification document'
   c1_neverattendsch_declined '44. Reason: Declined'
   c1_neverattendsch_dk '44. Reason: Donâ€™t know'
   c2_countrylivedin '1. Have you lived in another country for 6 months or longer?'
   c2_bornraisedke '1.a Were you born and raised in Kenya?'
   c2_differentcountrylivedin    '1b. Confirm: Have you lived in another country for 6+ months, eve' +
   'n as a child?'
   c2_countryresidedin    '2.In what country did you last reside for 6 months or longer befo' +
   're settling in '
   c2_countryresidedin_other    '2.In what country did you last reside for 6 months or longer befo' +
   're settling in '
   c2_whenlivein_startyear    '3. Start year of living in country last resided for 6+ months bef' +
   'ore Kenya'
   c2_whenlivein_endyear    '3. End year of living in country last resided for 6+ months befor' +
   'e Kenya'
   c2_isitorigincountry    '4. Is the country last resided before Kenya your country of origi' +
   'n?'
   c2_origincountry '4a. What is your country of origin?'
   c2_raisedin '5.Were you raised in your country of origin}'
   c2_whereraised '5a. Where were you raised?'
   c2_arrivedcurrresidence '7.What year did you arrive in your current place of residence?'
   c2_maritalstatus '8.What is your marital status?'
   c2_marriageplace '9.Where did you get married/started residing with your partner?'
   c2_marriageyr    '10. How old were you when you started living with your current pa' +
   'rtner?'
   c2_mainoccupation '11.What is your main occupation status?'
   c2_mainoccupationcountry    '12.What is your main employment status in the country where you l' +
   'ast resided?'
   c2_mainoccupationorigin    '13.What is your main employment status in your country of origin?'
   c2_pastyearlivingstatus    '1. In the past year, did your husband/partner live with you all o' +
   'r some time?'
   c2_child_biological    '2. Do you take care of biological children who are 14 years or yo' +
   'unger?'
   c2_child_nonbiological    '2. Do you take care of non-biological children who are 14 years o' +
   'r younger?'
   c2_child_notlivewithme    '2. Do you take care of children 14 years or younger who do not li' +
   've with you?'
   c2_child_no '2. Do you take care of children 14 years or younger: No'
   c2_child_declined '2. Do you take care of children 14 years or younger: Declined'
   c2_child_dk    '2. Do you take care of children 14 years or younger: Donâ€™t know'
   c2_receivepayment    '2a. Do you receive a payment or compensation for taking care of s' +
   'uch children?'
   c2_wifeabuse_none '3. Husband justified in hitting wife: None'
   c2_wifeabuse_goesout    '3. Husband justified in hitting wife: If she goes out without tel' +
   'ling him'
   c2_wifeabuse_neglects    '3. Husband justified in hitting wife: If she neglects the childre' +
   'n'
   c2_wifeabuse_argues '3. Husband justified in hitting wife: If she argues with him'
   c2_wifeabuse_sex    '3. Husband justified in hitting wife: If she refuses to have sex ' +
   'with him'
   c2_wifeabuse_food '3. Husband justified in hitting wife: If she burns the food'
   c2_wifeabuse_declined '3. Husband justified in hitting wife: Declined'
   c2_wifeabuse_dk '3. Husband justified in hitting wife: Donâ€™t know'
   c2_marriageage '4.  At what age is it acceptable for a woman to get married?'
   c2_womanmarriageagelstresided    '4a. The acceptable marriage age for women in your last country of' +
   ' residence'
   c2_womanmarriageagecountorig    '4b. The acceptable marriage age for women in your country of orig' +
   'in'
   c2_readnewsoften '5. How often do you read a newspaper or a magazine?'
   c2_readnewspaperfreqsltreside    '5a. Do you read newspapers/magazines as often as in your last cou' +
   'ntry of residen'
   c2_readnewspapercountorigin    '5b. Do you read newspapers/magazines as often as in your country ' +
   'of origin?'
   c2_listenradiofreq '6. How often do you listen to the radio?'
   c2_listenradiolstresided    '6a. Do you listen to the radio as often as in your last country o' +
   'f residence?'
   c2_listenradiocountorigin    '6b. Do you listen to the radio as often as in your country of ori' +
   'gin?'
   c2_internetaccessfreq '6c. How often do you access internet?'
   c2_internetaccesslstresided    '6d. Do you have internet as often as in your last country of resi' +
   'dence?'
   c2_internetaccesscountorigin    '6e. Do you access internet as often as you did in your country of' +
   ' origin?'
   c2_watchtvfreq '7. How often do you watch television?'
   c2_watchtvfreqlastresided    '7a Do you watch TV as often as you did in the country where you l' +
   'ast resided?'
   c2_watchtvcountryoforigin    '7b. Do you watch TV as often as you did in in your country of ori' +
   'gin ?'
   c2_fpmethod_femalesterile    '8.Ways a couple can use to delay a pregnancy: Female Sterilizatio' +
   'n'
   c2_fpmethod_malesterile    '8.Ways a couple can use to delay a pregnancy:Male Sterilization (' +
   'vasectomy)'
   c2_fpmethod_iud '8.Ways a couple can use to delay a pregnancy:IUD'
   c2_fpmethod_injectable '8.Ways a couple can use to delay a pregnancy:Injectables'
   c2_fpmethod_implants '8.Ways a couple can use to delay a pregnancy:Implants (Norplant)'
   c2_fpmethod_pill '8.Ways a couple can use to delay a pregnancy:Pill'
   c2_fpmethod_malecondom '8.Ways a couple can use to delay a pregnancy:Male Condom'
   c2_fpmethod_femalecondom '8.Ways a couple can use to delay a pregnancy:Female Condom'
   c2_fpmethod_lam    '8.Ways a couple can use to delay a pregnancy:Lactational Amenorrh' +
   'ea Method (LAM)'
   c2_fpmethod_rhythm    '8.Ways a couple can use to delay a pregnancy:Rhythm Method (safe ' +
   'days)'
   c2_fpmethod_withdrawal '8.Ways a couple can use to delay a pregnancy:Withdrawal'
   c2_fpmethod_econtraception    '8.Ways a couple can use to delay a pregnancy:Emergency Contracept' +
   'ion'
   c2_heardofmethods '8a Where did you hear about this/these method/s?'
   c2_fcircumcisionacceptlstreside    '9a. Do you think female circumcision is accepted in your last cou' +
   'ntry of residen'
   c2_fcircumcisionacceptorigin    '9b. Do you think female circumcision is accepted in your country ' +
   'of origin?'
   c2_fcircumcisionacceptcomunity    '9c In your opinion, is female circumcision an accepted practice i' +
   'n Kenya?'
   c2_fcircumcisioncontinuity    '9d Do you think that female circumcision should be continued or s' +
   'topped'
   c2_fpsourcelstfewmnth_radio    '10. Sources of hearing about family planning last few months:Radi' +
   'o'
   c2_fpsourcelstfewmnth_tv    '10. Sources of hearing about family planning last few months:Tele' +
   'vision'
   c2_fpsourcelstfewmnth_news    '10. Sources of hearing about family planning last few months:News' +
   'paper/magazine'
   c2_fpsourcelstfewmnth_social    '10. Sources of hearing about family planning last few months:Soci' +
   'al Media'
   c2_fpsourcelstfewmnth_internet    '10. Sources of hearing about family planning last few months:Inte' +
   'rnet'
   c2_fpsourcelstfewmnth_none    '10. Sources of hearing about family planning last few months:None'
   c2_fpsourcelstfewmnth_declined    '10. Sources of hearing about family planning last few months:Decl' +
   'ined'
   c2_fpsourcelstfewmnth_dk    '10. Sources of hearing about family planning last few months:Don' +
   'â€™t know'
   c2_fpsourcelst12mnth_pforums '11.Fam planning source 12 months: Public forum/gathering'
   c2_fpsourcelst12mnth_posters '11.Fam planning source 12 months: Informational material'
   c2_fpsourcelst12mnth_hworker '11.Fam planning source 12 months: Health worker/professional'
   c2_fpsourcelst12mnth_social '11.Fam planning source 12 months: Social media platforms'
   c2_fpsourcelst12mnth_email    '11.Fam planning source 12 months: mobile phone through text messa' +
   'ge or email'
   c2_fpsourcelst12mnth_political    '11.Fam planning source 12 months: Political/religious/community l' +
   'eaders'
   c2_fpsourcelst12mnth_none '11.Fam planning source 12 months:None'
   c2_fpsourcelst12mnth_declined '11.Fam planning source 12 months:Declined'
   c2_fpsourcelst12mnth_dk '11.Fam planning source 12 months:Donâ€™t know'
   c2_canacquirecondoms    '12. Do you know of a place where a person can get male or female ' +
   'condoms?'
   c2_acquirecondomslstreside    '12a Did you know where to get condoms in your last country of res' +
   'idence?'
   c2_acquirecondomcountorigin '12b Did you know where to get condoms in your country of origin?'
   c2_everheardaids '13. Have you ever heard of an illness called AIDS?'
   c2_heardaidsfrom '14 Where did you hear about AIDS?'
   c2_reducegetgaids_none '15. Reduce AIDS risk :None'
   c2_reducegetgaids_sexpartner    '15. Reduce AIDS risk: One uninfected partner with no other partne' +
   'rs'
   c2_reducegetgaids_condom '15. Reduce AIDS risk :Using a condom every time'
   c2_reducegetgaids_nosex '15. Reduce AIDS risk :No sexual intercourse'
   c2_reducegetgaids_decline '15. Reduce AIDS risk :Declined'
   c2_reducegetgaids_dk '15. Reduce AIDS risk :Donâ€™t know'
   c2_scenariogetaids_none '16.Is it possible to get the AIDS virus:None'
   c2_scenariogetaids_sexpartner    '16.Is it possible to get the AIDS virus:Sharing food with a perso' +
   'n who has AIDS'
   c2_scenariogetaids_condom    '16.Is it possible to get the AIDS virus:Through witchcraft/supern' +
   'atural means'
   c2_scenariogetaids_nosex '16.Is it possible to get the AIDS virus:Through mosquito bites'
   c2_scenariogetaids_decline '16.Is it possible to get the AIDS virus:Declined'
   c2_scenariogetaids_dk '16.Is it possible to get the AIDS virus:Donâ€™t know'
   c2_healthypersonhaveaids    '17. Is it possible for a healthy-looking person to have the AIDS ' +
   'virus?'
   c2_mombabyaidstrans_none    '18.Can the virus that causes AIDS be transmitted from a mother:No' +
   'ne'
   c2_mombabyaidstrans_preg    '18.Can the virus that causes AIDS be transmitted from a mother:Du' +
   'ring pregnancy'
   c2_mombabyaidstrans_delivery    '18.Can the virus that causes AIDS be transmitted from a mother:Du' +
   'ring delivery'
   c2_mombabyaidstrans_breast    '18.Can the virus that causes AIDS be transmitted from a mother:By' +
   ' breastfeeding'
   c2_mombabyaidstrans_declined    '18.Can the virus that causes AIDS be transmitted from a mother:De' +
   'clined'
   c2_mombabyaidstrans_dk    '18.Can the virus that causes AIDS be transmitted from a mother:Do' +
   'nâ€™t know'
   c2_partnerearningsdecision    '19. Now, who usually decides how your husbandâ€™s/partnerâ€™s ear' +
   'nings will be used?'
   c2_partnerearncountorigin    '19a. Decision maker on how to use partnerâ€™s earnings in your co' +
   'untry of origin'
   c2_partnerearnlstresided    '19b. Decision maker on how to use partnerâ€™s earnings in country' +
   ' last resided '
   c2_yourearningsdecision '19c. Decision maker on how your earnings will be used?'
   c2_yourearningscountorigin    '19d. Decision maker on how your earnings were used in your countr' +
   'y of origin?'
   c2_yourearningslstresided    '9e. Decision maker on how to use your earnings in the country las' +
   't resided'
   c2_seekpermonwrk_no '20. Need permision to work:No'
   c2_seekpermonwrk_partner '20. Need permision to work:Yes, from Husband/Partner'
   c2_seekpermonwrk_father '20. Need permision to work:Yes, from father/male guardian'
   c2_seekpermonwrk_mother '20. Need permision to work:Yes, from mother/female guardian'
   c2_seekpermonwrk_brother '20. Need permision to work:Yes, from brother'
   c2_seekpermonwrk_sister '20. Need permision to work:Yes, from sister'
   c2_seekpermonwrk_uncle '20. Need permision to work:Yes, from uncle'
   c2_seekpermonwrk_aunt '20. Need permision to work:Yes, from aunt'
   c2_seekpermonwrk_son '20. Need permision to work:Yes, from son'
   c2_seekpermonwrk_daughter '20. Need permision to work:Yes, from daughter'
   c2_seekpermonwrk_fatherinlaw '20. Need permision to work:Yes, from father-in-law'
   c2_seekpermonwrk_motherinlaw '20. Need permision to work:Yes, from mother-in-law'
   c2_seekpermonwrk_sombodyelse '20. Need permision to work:Yes, from somebody else'
   c2_seekpermonwrk_decline '20. Need permision to work:Declined'
   c2_seekpermonwrk_dk '20. Need permision to work:Donâ€™t know'
   c2_seekpermlstresided_no '21.If need permission to work in cntry last resided from:No'
   c2_seekpermlstresided_partner    '21.If need permission to work in cntry last resided:Yes, from Hus' +
   'band/Partner'
   c2_seekpermlstresided_father    '21.If need permission to work in cntry last resided:Yes, father/m' +
   'ale guardian'
   c2_seekpermlstresided_mother    '21.If need permission to work in cntry last resided:Yes, mother/f' +
   'emale guardian'
   c2_seekpermlstresided_brother    '21.If need permission to work in cntry last resided from:Yes, fro' +
   'm brother'
   c2_seekpermlstresided_sister    '21.If need permission to work in cntry last resided from:Yes, fro' +
   'm sister'
   c2_seekpermlstresided_uncle    '21.If need permission to work in cntry last resided from:Yes, fro' +
   'm uncle'
   c2_seekpermlstresided_aunt    '21.If need permission to work in cntry last resided from:Yes, fro' +
   'm aunt'
   c2_seekpermlstresided_son    '21.If need permission to work in cntry last resided from:Yes, fro' +
   'm son'
   c2_seekpermlstresided_daughter    '21.If need permission to work in cntry last resided from:Yes, fro' +
   'm daughter'
   c2_seekpermlstresided_fatherinla    '21.If need permission to work in cntry last resided from:Yes, fro' +
   'm father-in-law'
   c2_seekpermlstresided_motherinla    '21.If need permission to work in cntry last resided from:Yes, fro' +
   'm mother-in-law'
   c2_seekpermlstresided_somebodyel    '21.If need permission to work in cntry last resided from:Yes, fro' +
   'm somebody else'
   c2_seekpermlstresided_decline    '21.If need permission to work in cntry last resided from:Declined'
   c2_seekpermlstresided_dk    '21.If need permission to work in cntry last resided from:Donâ€™t ' +
   'know'
   c2_seekpermorigin_no '21a.If need permission to work in origin cntry from:No'
   c2_seekpermorigin_partner    '21a.If need permission to work in origin cntry from:Yes, from Hus' +
   'band / Partner'
   c2_seekpermorigin_father    '21a.If need permission to work in origin cntry:Yes, from father/m' +
   'ale guardian'
   c2_seekpermorigin_mother    '21a.If need permission to work in origin cntry:Yes, from mother/f' +
   'emale guardian'
   c2_seekpermorigin_brother    '21a.If need permission to work in origin cntry from:Yes, from bro' +
   'ther'
   c2_seekpermorigin_sister    '21a.If need permission to work in origin cntry from:Yes, from sis' +
   'ter'
   c2_seekpermorigin_uncle    '21a.If need permission to work in origin cntry from:Yes, from unc' +
   'le'
   c2_seekpermorigin_aunt    '21a.If need permission to work in origin cntry from:Yes, from aun' +
   't'
   c2_seekpermorigin_son    '21a.If need permission to work in origin cntry from:Yes, from son'
   c2_seekpermorigin_daughter    '21a.If need permission to work in origin cntry from:Yes, from dau' +
   'ghter'
   c2_seekpermorigin_fatherinlaw    '21a.If need permission to work in origin cntry from:Yes, from fat' +
   'her-in-law'
   c2_seekpermorigin_motherinlaw    '21a.If need permission to work in origin cntry from:Yes, from mot' +
   'her-in-law'
   c2_seekpermorigin_somebodyelse    '21a.If need permission to work in origin cntry from:Yes, from som' +
   'ebody else'
   c2_seekpermorigin_decline '21a.If need permission to work in origin cntry from:Declined'
   c2_seekpermorigin_dk '21a.If need permission to work in origin cntry from:Donâ€™t know'
   c2_healthcaredecision '22. Who usually makes decisions about health care for yourself?'
   c2_healthcaredecisionresid    '22a. Who made decisions about health care for yourself country la' +
   'st resided?'
   c2_healthcaredecisioncountorigin    '22b. Who made decisions about health care for yourself in your co' +
   'untry of origin'
   c2_hhpurchasesdecision    '23. Who usually makes decisions about making major household purc' +
   'hases?'
   c2_hhpurchasesdecisionresided    '23a. Who made decisions about major household purchases in countr' +
   'y last resided?'
   c2_hhpurchasesdecisionorigin    '23b. Who made decisions about major household purchases in your c' +
   'ountry of origi'
   c2_familyvisitsmakesdecision    '24. Who usually makes decisions about visits to your family or re' +
   'latives?'
   c2_famvisitdecisionlstreside    '24a.Who made decisions about visits to family/relatives the count' +
   'ry last resided'
   c2_famvisitdecisionorigin    '24b. Who made decisions about visits to your family/relatives in ' +
   'country of orig'
   c2_notosexualintercourse    '25. Can you say no to your partner if you do not want to have sex' +
   'ual intercourse'
   c2_condomusage    '26. Could you ask your (husband/partner) to use a condom if you w' +
   'anted him to?'
   c3_languageused_kiswahili '2.In which language was this interview conducted:Kiswahili'
   c3_languageused_turkana '2.In which language was this interview conducted:Turkana'
   c3_languageused_somali '2.In which language was this interview conducted:Somali'
   c3_languageused_arabic '2.In which language was this interview conducted:Arabic'
   c3_languageused_english '2.In which language was this interview conducted:English'
   c3_languageused_jubaarabic '2.In which language was this interview conducted:Juba Arabic'
   c3_languageused_other '2a.Respondentâ€™s skill in speaking and understanding:Other'
   c3_speech_kiswahili '2a.Respondentâ€™s skill in speaking and understanding:Kiswahili'
   c3_speech_turkana '2a.Respondentâ€™s skill in speaking and understanding:Turkana'
   c3_speech_somali '2a.Respondentâ€™s skill in speaking and understanding:Somali'
   c3_speech_arabic '2a.Respondentâ€™s skill in speaking and understanding:Arabic'
   c3_speech_english '2a.Respondentâ€™s skill in speaking and understanding:English'
   c3_speech_jubaarabic    '2a.Respondentâ€™s skill in speaking and understanding:Juba Arabic'
   c3_speech_other    '2a.Respondentâ€™s skill in speaking and understanding:Other speci' +
   'fied' .

VALUE LABELS
 strata_sampled strata_actual
     1 'Kakuma Refugees'
     2 'Kalobeyei Refugees'
     3 'Turkana Hosts'
     4 'Dadaab Refugees'
     5 'Dadaab Hosts'
     6 'Nairobi Refugees'
     7 'Nairobi Hosts'
     8 'Other Urban Refugees'
     9 'Other Urban Hosts' /
 groups_location_status
     1 'Camp refugees'
     2 'Camp hosts'
     3 'Urban refugees'
     4 'Urban hosts' /
 groups_status
     0 'Camp'
     1 'Urban' /
 c1_age1a
     1 '<20'
     2 '20-24'
     3 '25-29'
     4 '30-34'
     5 '35-39'
     6 '40-44'
     7 '45-49'
     8 '50-54'
     9 '55-59'
     10 '60-64'
     11 '65+' /
 c1_statusa1
     1 'Refugee'
     2 'Host' /
 c1_attendedschool
     0 'No'
     1 'Yes' /
 c1_educlevelcat
     1 'No schooling'
     2 'Primary'
     3 'Secondary'
     4 'Tertiary'
     5 'Other' /
 c1_neverattendsch_schoolcost
     0 'No'
     1 'Yes' /
 c1_neverattendsch_lacktoilet
     0 'No'
     1 'Yes' /
 c1_neverattendsch_lackteachers
     0 'No'
     1 'Yes' /
 c1_neverattendsch_illness
     0 'No'
     1 'Yes' /
 c1_neverattendsch_disability
     0 'No'
     1 'Yes' /
 c1_neverattendsch_famillness
     0 'No'
     1 'Yes' /
 c1_neverattendsch_famdisability
     0 'No'
     1 'Yes' /
 c1_neverattendsch_nointerest
     0 'No'
     1 'Yes' /
 c1_neverattendsch_parents
     0 'No'
     1 'Yes' /
 c1_neverattendsch_hadtowork
     0 'No'
     1 'Yes' /
 c1_neverattendsch_toofar
     0 'No'
     1 'Yes' /
 c1_neverattendsch_sanitary
     0 'No'
     1 'Yes' /
 c1_neverattendsch_conflicts
     0 'No'
     1 'Yes' /
 c1_neverattendsch_insecurity
     0 'No'
     1 'Yes' /
 c1_neverattendsch_safety
     0 'No'
     1 'Yes' /
 c1_neverattendsch_marriage
     0 'No'
     1 'Yes' /
 c1_neverattendsch_teachers
     0 'No'
     1 'Yes' /
 c1_neverattendsch_pregnancy
     0 'No'
     1 'Yes' /
 c1_neverattendsch_notadmit
     0 'No'
     1 'Yes' /
 c1_neverattendsch_pressure
     0 'No'
     1 'Yes' /
 c1_neverattendsch_orphaned
     0 'No'
     1 'Yes' /
 c1_neverattendsch_identificat
     0 'No'
     1 'Yes' /
 c1_neverattendsch_declined
     0 'No'
     1 'Yes' /
 c1_neverattendsch_dk
     0 'No'
     1 'Yes' /
 c2_countrylivedin
     0 'No'
     1 'Yes' /
 c2_bornraisedke
     0 'No'
     1 'Yes' /
 c2_differentcountrylivedin
     0 'No'
     1 'Yes' /
 c2_countryresidedin
     1 'Kenya'
     2 'Somali'
     3 'South Sudan'
     4 'DRC'
     5 'Other' /
 c2_isitorigincountry
     0 'No'
     1 'Yes' /
 c2_origincountry
     1 'Kenya'
     2 'Somali'
     3 'South Sudan'
     4 'DRC'
     5 'Other' /
 c2_raisedin
     0 'No'
     1 'Yes' /
 c2_whereraised
     1 'Kenya'
     2 'Somali'
     3 'South Sudan'
     4 'DRC'
     5 'Other' /
 c2_maritalstatus
     1 'Married monogamous'
     2 'Married polygamous'
     3 'Living together'
     4 'Separated'
     5 'Divorced'
     6 'Widow or widower'
     7 'Never married' /
 c2_marriageplace
     1 'In country of origin'
     2 'In transit country (between country of origin or of last residence and Kenya)'
     3 'In country of last residence (for those who lived for 1+ years in another countr'
     4 'In Kenya' /
 c2_marriageyr
     1 '<20'
     2 '20-24'
     3 '25-29'
     4 '30-34'
     5 '35-39'
     6 '40-44'
     7 '45-49'
     8 '50-54'
     9 '55-59'
     10 '60-64'
     11 '65+' /
 c2_mainoccupation
     -99 'Not working and not looking for work'
     -77 'Other'
     1 'Employed (working for pay or profit)'
     2 'Unemployed (seeking employment)'
     3 'Full time student/ pupil'
     4 'Housewife/family responsibilities'
     5 'Retired/income recipient'
     6 'Contributing family worker (without pay)'
     7 'Volunteer'
     8 'Apprentice/intern/attache'
     9 'Not working and not looking for work' /
 c2_mainoccupationcountry
     -99 'Not working and not looking for work'
     -77 'Other'
     1 'Employed (working for pay or profit)'
     2 'Unemployed (seeking employment)'
     3 'Full time student/ pupil'
     4 'Housewife/family responsibilities'
     5 'Retired/income recipient'
     6 'Contributing family worker (without pay)'
     7 'Volunteer'
     8 'Apprentice/intern/attache'
     9 'Not working and not looking for work'
     10 'Was younger than 14 years when I left' /
 c2_mainoccupationorigin
     -99 'Not working and not looking for work'
     -77 'Other'
     1 'Employed (working for pay or profit)'
     2 'Unemployed (seeking employment)'
     3 'Full time student/ pupil'
     4 'Housewife/family responsibilities'
     5 'Retired/income recipient'
     6 'Contributing family worker (without pay)'
     7 'Volunteer'
     8 'Apprentice/intern/attache'
     9 'Not working and not looking for work'
     10 'Was younger than 14 years when I left' /
 c2_pastyearlivingstatus
     0 'No time during the last year'
     1 'Lived together less than 3 months during the last year'
     2 'Lived together more than 3 months but less than 6 months during the last year'
     3 'Lived together at least 6 months but not always during the last year'
     4 'Always lived together during the last year' /
 c2_child_biological
     0 'No'
     1 'Yes' /
 c2_child_nonbiological
     0 'No'
     1 'Yes' /
 c2_child_notlivewithme
     0 'No'
     1 'Yes' /
 c2_child_no
     0 'No'
     1 'Yes' /
 c2_child_declined
     0 'No'
     1 'Yes' /
 c2_child_dk
     0 'No'
     1 'Yes' /
 c2_receivepayment
     -98 'Don’t know'
     -97 'Declined'
     0 'No'
     1 'Yes' /
 c2_wifeabuse_none
     0 'No'
     1 'Yes' /
 c2_wifeabuse_goesout
     0 'No'
     1 'Yes' /
 c2_wifeabuse_neglects
     0 'No'
     1 'Yes' /
 c2_wifeabuse_argues
     0 'No'
     1 'Yes' /
 c2_wifeabuse_sex
     0 'No'
     1 'Yes' /
 c2_wifeabuse_food
     0 'No'
     1 'Yes' /
 c2_wifeabuse_declined
     0 'No'
     1 'Yes' /
 c2_wifeabuse_dk
     0 'No'
     1 'Yes' /
 c2_marriageage
     -98 "Don't Know"
     -97 'Declined'
     1 'Under 15 years of age'
     2 'Between 15 and 17 years of age'
     3 'Between 18 and 21 years of age'
     4 'Over 21 years of age' /
 c2_womanmarriageagelstresided
     -98 'Don’t know'
     -97 'Declined'
     1 'Under 15 years of age'
     2 'Between 15 and 17 years of age'
     3 'Between 18 and 21 years of age'
     4 'Over 21 years of age' /
 c2_womanmarriageagecountorig
     -98 'Don’t know'
     -97 'Declined'
     1 'Under 15 years of age'
     2 'Between 15 and 17 years of age'
     3 'Between 18 and 21 years of age'
     4 'Over 21 years of age' /
 c2_readnewsoften
     -98 'Don’t know'
     -97 'Declined'
     1 'At least once a week'
     2 'Less than once a week'
     3 'Not at all' /
 c2_readnewspaperfreqsltreside
     1 'More often in Kenya'
     2 'As often as in country of last residence/country of origin'
     3 'Less often in Kenya' /
 c2_readnewspapercountorigin
     1 'More often in Kenya'
     2 'As often as in country of last residence/country of origin'
     3 'Less often in Kenya' /
 c2_listenradiofreq
     -98 'Don’t know'
     -97 'Declined'
     1 'At least once a week'
     2 'Less than once a week'
     3 'Not at all' /
 c2_listenradiolstresided
     1 'More often in Kenya'
     2 'As often as in country of last residence/country of origin'
     3 'Less often in Kenya' /
 c2_listenradiocountorigin
     1 'More often in Kenya'
     2 'As often as in country of last residence/country of origin'
     3 'Less often in Kenya' /
 c2_internetaccessfreq
     -98 'Don’t know'
     -97 'Declined'
     1 'At least once a week'
     2 'Less than once a week'
     3 'Not at all' /
 c2_internetaccesslstresided
     1 'More often in Kenya'
     2 'As often as in country of last residence/country of origin'
     3 'Less often in Kenya' /
 c2_internetaccesscountorigin
     1 'More often in Kenya'
     2 'As often as in country of last residence/country of origin'
     3 'Less often in Kenya' /
 c2_watchtvfreq
     -98 'Don’t know'
     -97 'Declined'
     1 'At least once a week'
     2 'Less than once a week'
     3 'Not at all' /
 c2_watchtvfreqlastresided
     1 'More often in Kenya'
     2 'As often as in country of last residence/country of origin'
     3 'Less often in Kenya' /
 c2_watchtvcountryoforigin
     1 'More often in Kenya'
     2 'As often as in country of last residence/country of origin'
     3 'Less often in Kenya' /
 c2_fpmethod_femalesterile
     -98 'Don’t know'
     -97 'Declined'
     0 'No'
     1 'Yes' /
 c2_fpmethod_malesterile
     -98 'Don’t know'
     -97 'Declined'
     0 'No'
     1 'Yes' /
 c2_fpmethod_iud
     -98 'Don’t know'
     -97 'Declined'
     0 'No'
     1 'Yes' /
 c2_fpmethod_injectable
     -98 'Don’t know'
     -97 'Declined'
     0 'No'
     1 'Yes' /
 c2_fpmethod_implants
     -98 'Don’t know'
     -97 'Declined'
     0 'No'
     1 'Yes' /
 c2_fpmethod_pill
     -98 'Don’t know'
     -97 'Declined'
     0 'No'
     1 'Yes' /
 c2_fpmethod_malecondom
     -98 'Don’t know'
     -97 'Declined'
     0 'No'
     1 'Yes' /
 c2_fpmethod_femalecondom
     -98 'Don’t know'
     -97 'Declined'
     0 'No'
     1 'Yes' /
 c2_fpmethod_lam
     -98 'Don’t know'
     -97 'Declined'
     0 'No'
     1 'Yes' /
 c2_fpmethod_rhythm
     -98 'Don’t know'
     -97 'Declined'
     0 'No'
     1 'Yes' /
 c2_fpmethod_withdrawal
     -98 'Don’t know'
     -97 'Declined'
     0 'No'
     1 'Yes' /
 c2_fpmethod_econtraception
     -98 'Don’t know'
     -97 'Declined'
     0 'No'
     1 'Yes' /
 c2_heardofmethods
     1 'In country of origin'
     2 'In transit country (between country of origin/last residence and Kenya)'
     3 'In country of last residence'
     4 'In Kenya' /
 c2_fcircumcisionacceptlstreside
     -98 'Don’t know'
     -97 'Declined'
     0 'No'
     1 'Yes' /
 c2_fcircumcisionacceptorigin
     -98 'Don’t know'
     -97 'Declined'
     0 'No'
     1 'Yes' /
 c2_fcircumcisionacceptcomunity
     -98 'Don’t know'
     -97 'Declined'
     0 'No'
     1 'Yes' /
 c2_fcircumcisioncontinuity
     -98 'Don’t know'
     -97 'Declined'
     1 'Continued'
     2 'Stopped'
     3 'Depends' /
 c2_fpsourcelstfewmnth_radio
     0 'No'
     1 'Yes' /
 c2_fpsourcelstfewmnth_tv
     0 'No'
     1 'Yes' /
 c2_fpsourcelstfewmnth_news
     0 'No'
     1 'Yes' /
 c2_fpsourcelstfewmnth_social
     0 'No'
     1 'Yes' /
 c2_fpsourcelstfewmnth_internet
     0 'No'
     1 'Yes' /
 c2_fpsourcelstfewmnth_none
     0 'No'
     1 'Yes' /
 c2_fpsourcelstfewmnth_declined
     0 'No'
     1 'Yes' /
 c2_fpsourcelstfewmnth_dk
     0 'No'
     1 'Yes' /
 c2_fpsourcelst12mnth_pforums
     0 'No'
     1 'Yes' /
 c2_fpsourcelst12mnth_posters
     0 'No'
     1 'Yes' /
 c2_fpsourcelst12mnth_hworker
     0 'No'
     1 'Yes' /
 c2_fpsourcelst12mnth_social
     0 'No'
     1 'Yes' /
 c2_fpsourcelst12mnth_email
     0 'No'
     1 'Yes' /
 c2_fpsourcelst12mnth_political
     0 'No'
     1 'Yes' /
 c2_fpsourcelst12mnth_none
     0 'No'
     1 'Yes' /
 c2_fpsourcelst12mnth_declined
     0 'No'
     1 'Yes' /
 c2_fpsourcelst12mnth_dk
     0 'No'
     1 'Yes' /
 c2_canacquirecondoms
     -98 'Don’t know'
     -97 'Declined'
     0 'No'
     1 'Yes' /
 c2_acquirecondomslstreside
     -98 'Don’t know'
     -97 'Declined'
     0 'No'
     1 'Yes' /
 c2_acquirecondomcountorigin
     -98 'Don’t know'
     -97 'Declined'
     0 'No'
     1 'Yes' /
 c2_everheardaids
     -98 'Don’t know'
     -97 'Declined'
     0 'No'
     1 'Yes' /
 c2_heardaidsfrom
     1 'In country of origin'
     2 'In transit country (between country of origin/last residence and Kenya)'
     3 'In country of last residence'
     4 'In Kenya' /
 c2_reducegetgaids_none
     0 'No'
     1 'Yes' /
 c2_reducegetgaids_sexpartner
     0 'No'
     1 'Yes' /
 c2_reducegetgaids_condom
     0 'No'
     1 'Yes' /
 c2_reducegetgaids_nosex
     0 'No'
     1 'Yes' /
 c2_reducegetgaids_decline
     0 'No'
     1 'Yes' /
 c2_reducegetgaids_dk
     0 'No'
     1 'Yes' /
 c2_scenariogetaids_none
     0 'No'
     1 'Yes' /
 c2_scenariogetaids_sexpartner
     0 'No'
     1 'Yes' /
 c2_scenariogetaids_condom
     0 'No'
     1 'Yes' /
 c2_scenariogetaids_nosex
     0 'No'
     1 'Yes' /
 c2_scenariogetaids_decline
     0 'No'
     1 'Yes' /
 c2_scenariogetaids_dk
     0 'No'
     1 'Yes' /
 c2_healthypersonhaveaids
     -98 'Don’t know'
     -97 'Declined'
     0 'No'
     1 'Yes' /
 c2_mombabyaidstrans_none
     0 'No'
     1 'Yes' /
 c2_mombabyaidstrans_preg
     0 'No'
     1 'Yes' /
 c2_mombabyaidstrans_delivery
     0 'No'
     1 'Yes' /
 c2_mombabyaidstrans_breast
     0 'No'
     1 'Yes' /
 c2_mombabyaidstrans_declined
     0 'No'
     1 'Yes' /
 c2_mombabyaidstrans_dk
     0 'No'
     1 'Yes' /
 c2_partnerearningsdecision
     -98 'Don’t know'
     -97 'Declined'
     -77 'Somebody else'
     1 'Respodent'
     2 'Husband / Partner'
     3 'Respondent and Husband / Partner jointly'
     4 'Somebody else' /
 c2_partnerearncountorigin
     -98 'Don’t know'
     -97 'Declined'
     -77 'Somebody else'
     1 'Respodent'
     2 'Husband / Partner'
     3 'Respondent and Husband / Partner jointly'
     4 'Somebody else' /
 c2_partnerearnlstresided
     -98 'Don’t know'
     -97 'Declined'
     -77 'Somebody else (specify)'
     1 'Respondent'
     2 'Husband / Partner'
     3 'Respondent and Husband / Partner jointly' /
 c2_yourearningsdecision
     -98 'Don’t know'
     -97 'Declined'
     1 'Respodent'
     2 'Husband / Partner'
     3 'Respondent and Husband / Partner jointly'
     4 'Somebody else'
     5 'Mother/female guardian'
     6 'Brother'
     7 'Sister'
     8 'Uncle'
     9 'Aunt'
     10 'Son'
     11 'Daughter'
     12 'Father-in-law'
     13 'Mother-in-law'
     14 'Somebody else' /
 c2_yourearningscountorigin
     -98 'Don’t know'
     -97 'Declined'
     1 'Respodent'
     2 'Husband / Partner'
     3 'Respondent and Husband / Partner jointly'
     4 'Somebody else'
     5 'Mother/female guardian'
     6 'Brother'
     7 'Sister'
     8 'Uncle'
     9 'Aunt'
     10 'Son'
     11 'Daughter'
     12 'Father-in-law'
     13 'Mother-in-law'
     14 'Somebody else' /
 c2_yourearningslstresided
     -98 'Don’t know'
     -97 'Declined'
     1 'Respondent'
     2 'Husband / Partner'
     3 'Respondent and Husband / Partner jointly'
     4 'Father/male guardian'
     5 'Mother/female guardian'
     6 'Brother'
     7 'Sister'
     8 'Uncle'
     9 'Aunt'
     10 'Son'
     11 'Daughter'
     12 'Father-in-law'
     13 'Mother-in-law'
     14 'Somebody else' /
 c2_seekpermonwrk_no
     0 'No'
     1 'Yes' /
 c2_seekpermonwrk_partner
     0 'No'
     1 'Yes' /
 c2_seekpermonwrk_father
     0 'No'
     1 'Yes' /
 c2_seekpermonwrk_mother
     0 'No'
     1 'Yes' /
 c2_seekpermonwrk_brother
     0 'No'
     1 'Yes' /
 c2_seekpermonwrk_sister
     0 'No'
     1 'Yes' /
 c2_seekpermonwrk_uncle
     0 'No'
     1 'Yes' /
 c2_seekpermonwrk_aunt
     0 'No'
     1 'Yes' /
 c2_seekpermonwrk_son
     0 'No'
     1 'Yes' /
 c2_seekpermonwrk_daughter
     0 'No'
     1 'Yes' /
 c2_seekpermonwrk_fatherinlaw
     0 'No'
     1 'Yes' /
 c2_seekpermonwrk_motherinlaw
     0 'No'
     1 'Yes' /
 c2_seekpermonwrk_sombodyelse
     0 'No'
     1 'Yes' /
 c2_seekpermonwrk_decline
     0 'No'
     1 'Yes' /
 c2_seekpermonwrk_dk
     0 'No'
     1 'Yes' /
 c2_seekpermlstresided_no
     0 'No'
     1 'Yes' /
 c2_seekpermlstresided_partner
     0 'No'
     1 'Yes' /
 c2_seekpermlstresided_father
     0 'No'
     1 'Yes' /
 c2_seekpermlstresided_mother
     0 'No'
     1 'Yes' /
 c2_seekpermlstresided_brother
     0 'No'
     1 'Yes' /
 c2_seekpermlstresided_sister
     0 'No'
     1 'Yes' /
 c2_seekpermlstresided_uncle
     0 'No'
     1 'Yes' /
 c2_seekpermlstresided_aunt
     0 'No'
     1 'Yes' /
 c2_seekpermlstresided_son
     0 'No'
     1 'Yes' /
 c2_seekpermlstresided_daughter
     0 'No'
     1 'Yes' /
 c2_seekpermlstresided_fatherinla
     0 'No'
     1 'Yes' /
 c2_seekpermlstresided_motherinla
     0 'No'
     1 'Yes' /
 c2_seekpermlstresided_somebodyel
     0 'No'
     1 'Yes' /
 c2_seekpermlstresided_decline
     0 'No'
     1 'Yes' /
 c2_seekpermlstresided_dk
     0 'No'
     1 'Yes' /
 c2_seekpermorigin_no
     0 'No'
     1 'Yes' /
 c2_seekpermorigin_partner
     0 'No'
     1 'Yes' /
 c2_seekpermorigin_father
     0 'No'
     1 'Yes' /
 c2_seekpermorigin_mother
     0 'No'
     1 'Yes' /
 c2_seekpermorigin_brother
     0 'No'
     1 'Yes' /
 c2_seekpermorigin_sister
     0 'No'
     1 'Yes' /
 c2_seekpermorigin_uncle
     0 'No'
     1 'Yes' /
 c2_seekpermorigin_aunt
     0 'No'
     1 'Yes' /
 c2_seekpermorigin_son
     0 'No'
     1 'Yes' /
 c2_seekpermorigin_daughter
     0 'No'
     1 'Yes' /
 c2_seekpermorigin_fatherinlaw
     0 'No'
     1 'Yes' /
 c2_seekpermorigin_motherinlaw
     0 'No'
     1 'Yes' /
 c2_seekpermorigin_somebodyelse
     0 'No'
     1 'Yes' /
 c2_seekpermorigin_decline
     0 'No'
     1 'Yes' /
 c2_seekpermorigin_dk
     0 'No'
     1 'Yes' /
 c2_healthcaredecision
     -98 'Don’t know'
     -97 'Declined'
     1 'Respodent'
     2 'Husband / Partner'
     3 'Respondent and Husband / Partner jointly'
     4 'Father / Male guardian'
     5 'Mother / Female guardian'
     6 'Brother/ Sister'
     7 'Son/ Daughter'
     8 'Other relative'
     9 'Somebody else'
     10 'I never visited family or relatives'
     11 'Daughter'
     12 'Father-in-law'
     13 'Mother-in-law'
     14 'Somebody else' /
 c2_healthcaredecisionresid
     -98 'Don’t know'
     -97 'Declined'
     1 'Respodent'
     2 'Husband / Partner'
     3 'Respondent and Husband / Partner jointly'
     4 'Father / Male guardian'
     5 'Mother / Female guardian'
     6 'Brother/ Sister'
     7 'Son/ Daughter'
     8 'Other relative'
     9 'Somebody else'
     10 'I never visited family or relatives'
     11 'Daughter'
     12 'Father-in-law'
     13 'Mother-in-law'
     14 'Somebody else' /
 c2_healthcaredecisioncountorigin
     -98 'Don’t know'
     -97 'Declined'
     1 'Respodent'
     2 'Husband / Partner'
     3 'Respondent and Husband / Partner jointly'
     4 'Father / Male guardian'
     5 'Mother / Female guardian'
     6 'Brother/ Sister'
     7 'Son/ Daughter'
     8 'Other relative'
     9 'Somebody else'
     10 'I never visited family or relatives'
     11 'Daughter'
     12 'Father-in-law'
     13 'Mother-in-law'
     14 'Somebody else' /
 c2_hhpurchasesdecision
     -98 'Don’t know'
     -97 'Declined'
     1 'Respodent'
     2 'Husband / Partner'
     3 'Respondent and Husband / Partner jointly'
     4 'Father / Male guardian'
     5 'Mother / Female guardian'
     6 'Brother/ Sister'
     7 'Son/ Daughter'
     8 'Other relative'
     9 'Somebody else'
     10 'I never visited family or relatives'
     11 'Daughter'
     12 'Father-in-law'
     13 'Mother-in-law'
     14 'Somebody else' /
 c2_hhpurchasesdecisionresided
     -98 'Don’t know'
     -97 'Declined'
     1 'Respodent'
     2 'Husband / Partner'
     3 'Respondent and Husband / Partner jointly'
     4 'Father / Male guardian'
     5 'Mother / Female guardian'
     6 'Brother/ Sister'
     7 'Son/ Daughter'
     8 'Other relative'
     9 'Somebody else'
     10 'I never visited family or relatives'
     11 'Daughter'
     12 'Father-in-law'
     13 'Mother-in-law'
     14 'Somebody else' /
 c2_hhpurchasesdecisionorigin
     -98 'Don’t know'
     -97 'Declined'
     1 'Respodent'
     2 'Husband / Partner'
     3 'Respondent and Husband / Partner jointly'
     4 'Father / Male guardian'
     5 'Mother / Female guardian'
     6 'Brother/ Sister'
     7 'Son/ Daughter'
     8 'Other relative'
     9 'Somebody else'
     10 'I never visited family or relatives'
     11 'Daughter'
     12 'Father-in-law'
     13 'Mother-in-law'
     14 'Somebody else' /
 c2_familyvisitsmakesdecision
     -98 'Don’t know'
     -97 'Declined'
     1 'Respodent'
     2 'Husband / Partner'
     3 'Respondent and Husband / Partner jointly'
     4 'Father / Male guardian'
     5 'Mother / Female guardian'
     6 'Brother/ Sister'
     7 'Son/ Daughter'
     8 'Other relative'
     9 'Somebody else'
     10 'I never visited family or relatives'
     11 'Daughter'
     12 'Father-in-law'
     13 'Mother-in-law'
     14 'Somebody else'
     15 'I never visit family or relatives' /
 c2_famvisitdecisionlstreside
     -98 'Don’t know'
     -97 'Declined'
     1 'Respodent'
     2 'Husband / Partner'
     3 'Respondent and Husband / Partner jointly'
     4 'Father / Male guardian'
     5 'Mother / Female guardian'
     6 'Brother/ Sister'
     7 'Son/ Daughter'
     8 'Other relative'
     9 'Somebody else'
     10 'I never visited family or relatives'
     11 'Daughter'
     12 'Father-in-law'
     13 'Mother-in-law'
     14 'Somebody else'
     15 'I never visited family or relatives' /
 c2_famvisitdecisionorigin
     -98 'Don’t know'
     -97 'Declined'
     1 'Respodent'
     2 'Husband / Partner'
     3 'Respondent and Husband / Partner jointly'
     4 'Father / Male guardian'
     5 'Mother / Female guardian'
     6 'Brother/ Sister'
     7 'Son/ Daughter'
     8 'Other relative'
     9 'Somebody else'
     10 'I never visited family or relatives'
     11 'Daughter'
     12 'Father-in-law'
     13 'Mother-in-law'
     14 'Somebody else'
     15 'I never visited family or relatives' /
 c2_notosexualintercourse
     -98 'Don’t know'
     -97 'Declined'
     0 'No'
     1 'Yes' /
 c2_condomusage
     -98 'Don’t know'
     -97 'Declined'
     0 'No'
     1 'Yes' /
 c3_languageused_kiswahili
     0 'No'
     1 'Yes' /
 c3_languageused_turkana
     0 'No'
     1 'Yes' /
 c3_languageused_somali
     0 'No'
     1 'Yes' /
 c3_languageused_arabic
     0 'No'
     1 'Yes' /
 c3_languageused_english
     0 'No'
     1 'Yes' /
 c3_languageused_jubaarabic
     0 'No'
     1 'Yes' /
 c3_languageused_other
     0 'No'
     1 'Yes' /
 c3_speech_kiswahili c3_speech_turkana c3_speech_somali c3_speech_arabic c3_speech_english c3_speech_jubaarabic c3_speech_other
     1 'No problems'
     2 'A little difficulty'
     3 'Moderate difficulty'
     4 'Serious problems' / .


SAVE OUTFILE='.\wer.sav'.
